### ISSUE TITLE
bwa bam files under /tmp ?

### ISSUE THREAD

**Issue by marchoeppner** [bcgsc/arks#10]
Hi,
not entirely sure if this is tigmint, or arks that does it, but when running the arks pipeline with tigmint as optional step, it starts writing bam files into /tmp - a whole bunch of them.

Our machine has no shortage of RAM (1.5TB), so this seems unnecessary (if we could specify the amount of RAM to be used by the program, that is). Alternatively, it would be useful to be able to specify something other than /tmp since our system partition is not big enough for tens of GB of temp files.

Cheers,
Marc

**Comment by lcoombe** [comment]
Hi @marchoeppner,
Sorry for the delayed response -- I was on vacation last week.

The BAM files are written by tigmint (ARKS uses exact kmer matching instead of alignments) -- Here's the line from the ```tigmint-make``` script that generates the alignments:
```
# Align paired-end reads to the draft genome and sort by BX tag.
$(draft).%.sortbx.bam: %.fq.gz $(draft).fa.bwt
	$(gtime) bwa mem -t$t -pC $(draft).fa $< | samtools view -u -F4 | samtools sort -@$t -tBX -T$$(mktemp -u -t $@.XXXXXX) -o $@
```
The ```-T``` option for ```samtools sort``` above is specifying the temporary directory. Based on the ```man``` page for ```mktemp```, it looks like you can set the directory by setting the ```$TMPDIR``` variable or specifying ```-p```. Alternatively, for a quick fix, you could remove the ```-T$$(mktemp -u -t $@.XXXXXX)``` part of the command in your specific copy of the tigmint-make file and by default the temp files will be created in the current working directory.

Hope that helps!
Lauren

**Comment by lcoombe** [comment]
Hi @marchoeppner - I'll close this, but feel free to open another issue if you have further questions!
