### ISSUE TITLE
Error running demo of Arks

### ISSUE THREAD

**Issue by arunprasanna83** [bcgsc/arks#11]
Hello,
I tried to install Arks in my linux workstation. I did get arks and arks-make after ./configure and make install. I have added arks, arks-make and LINKS to path. I tried running ./runARKSdemo.sh and following is the error I encountered. Can you kindly let me know the issue & solution?. Btw, I have uncommented two lines in LINKS (#find bin, #use bloomFilter).

```
$./runARKSdemo.sh
Ensure the following are in your PATH: arks, LINKS, arks-make
	NOTE: arks-make Makefile is found in Examples directory of repo
Running ARKS makefile....
/usr/bin/time -v arks -p full -v -f test_scaffolds.renamed.fa -a test_reads_multiplicities.csv -c 5 -t 1 -j 0.55 -o 0 -m 50-6000 -k 30 -r 0.05 -e 30000 -z 500 -d 0 -b test_scaffolds_c5_m50-6000_k30_r0.05_e30000_z500 test_reads.fq.gz **|&** tee test_scaffolds_c5_m50-6000_k30_r0.05_e30000_z500_arks.log
/bin/sh: 1: Syntax error: "&" unexpected
/usr/local/bin/arks-make:147: recipe for target 'test_scaffolds_c5_m50-6000_k30_r0.05_e30000_z500_original.gv' failed
make: *** [test_scaffolds_c5_m50-6000_k30_r0.05_e30000_z500_original.gv] Error 2
```

I have another request to the team. Is it possible to release a conda installation ?. The installation of dependencies are very tedious. esp. BloomFilter. After spending hours browsing the issue, found in your issues page that it is not mandatory !. 
Best Regards,
AP

**Comment by lcoombe** [comment]
Hi @arunprasanna83 - I suspect that this issue is due to the version of bash that you're using. See this stack overflow post about this error: https://stackoverflow.com/questions/20553916/syntax-error-near-unexpected-token-using
I have not seen this issue when testing arks-make with bash v4.1.2 and v4.2.46.

As a short-term solution, you could remove ```|& tee $(patsubst %_original.gv,%,$@)_arks.log``` from the ```arks``` command (and the similar section from the LINKS command). This part is just piping the output of ARKS/LINKS to separate log files, so if you remove these parts it will just print to standard out. Or, you could try replacing ```|&``` with ```2>&1 |``` (disclaimer that I haven't tested that substitution, but I see it is suggested in that stack overflow post). I will look at using a more compatible method for logging to file in the arks-make file.

We don't currently have plans to release a conda installation for ARKS, but your request is noted! (The BloomFilter issue that you mention is specifically for LINKS.)

Hope that helps,
Lauren

**Comment by arunprasanna83** [comment]
> Hi @arunprasanna83 - I suspect that this issue is due to the version of bash that you're using. See this stack overflow post about this error: https://stackoverflow.com/questions/20553916/syntax-error-near-unexpected-token-using
> I have not seen this issue when testing arks-make with bash v4.1.2 and v4.2.46.
> 
> As a short-term solution, you could remove `|& tee $(patsubst %_original.gv,%,$@)_arks.log` from the `arks` command (and the similar section from the LINKS command). This part is just piping the output of ARKS/LINKS to separate log files, so if you remove these parts it will just print to standard out. Or, you could try replacing `|&` with `2>&1 |` (disclaimer that I haven't tested that substitution, but I see it is suggested in that stack overflow post). I will look at using a more compatible method for logging to file in the arks-make file.
> 
> We don't currently have plans to release a conda installation for ARKS, but your request is noted! (The BloomFilter issue that you mention is specifically for LINKS.)
> 
> Hope that helps,
> Lauren

Hi Lauren,
The bash version I am using is 4.4.19 in Ubuntu. In the arks-make file I removed all instances of '|&..... .log'. Re - [configure, make install].  Also the arks file in Arks subfolder is not readable by any text editor. Still I get the same error !.

Thanks,
Arun

**Comment by lcoombe** [comment]
Hi Arun,

The ```arks``` file compiled is a binary, so you won't be able to read it. If you run ```arks --help```, then you will be able to see the ARKS help page.

Could you please update with what error you are getting now (Copy the log here)? I'm guessing it must be different if you have removed the ```|&```, etc from the offending lines in arks-make (I wouldn't expect the same ```Syntax error: "&" unexpected``` if you didn't have ```&``` in the line anymore - I'm unable to reproduce the error you have above -- perhaps because we use Centos)

Lauren

**Comment by arunprasanna83** [comment]
> Hi Arun,
> 
> The `arks` file compiled is a binary, so you won't be able to read it. If you run `arks --help`, then you will be able to see the ARKS help page.
> 
> Could you please update with what error you are getting now (Copy the log here)? I'm guessing it must be different if you have removed the `|&`, etc from the offending lines in arks-make (I wouldn't expect the same `Syntax error: "&" unexpected` if you didn't have `&` in the line anymore - I'm unable to reproduce the error you have above -- perhaps because we use Centos)
> 
> Lauren

Hi Lauren,
Ok !. It's hard to figure out where the problem is !. However I installed it in other system with different configuration. Let me summarize it below, so that other users benefit !

Failed attempt: bash v4.4.19, gcc v 4.1.12, Ubuntu 18.04 LTS - |& error
Successful attempt: bash v4.2.46, gcc v 6(>=) 
1. create conda environment
2. Activate env
3. conda install -c bioconda links
4. configure && make => Initially, the compilation failed because, it was seeking google/sparsehash (compatible with gcc v>=6, lower versions were buggy).
5. conda install -c bioconda sparsehash or google-sparsehash
6. Include sparsehash in CXXFLAGS, CFLAGS
7. Configure and make install

I also had to do a minor tweak in arks-make file by replacing /usr/bin/time to time, since it is a server, it didn't point to /usr/bin rather had /local/bin or /bin..

Kindly test a version in bash v>4.2. It will be highly useful for novice like me to get a conda bundle !
Best,
Arun

**Comment by lcoombe** [comment]
Thanks @arunprasanna83 - So problem solved?
I tested ```arks-make``` with bash 4.4.19 on Centos, and it ran fine for me. And just so its clear, the error you showed about was due to ```arks-make```, not the binary ```arks```.

Just to make sure I know what solved your problem (so I can adjust ```arks-make``` accordingly):
* Changing /usr/bin/time to time
* Removing the ```|&``` sections of the commands 

Let me know if those were the adjustments you made!

**Comment by arunprasanna83** [comment]
> Thanks @arunprasanna83 - So problem solved?
> I tested `arks-make` with bash 4.4.19 on Centos, and it ran fine for me. And just so its clear, the error you showed about was due to `arks-make`, not the binary `arks`.
> 
> Just to make sure I know what solved your problem (so I can adjust `arks-make` accordingly):
> 
>     * Changing /usr/bin/time to time
> 
>     * Removing the `|&` sections of the commands

In the successful attempt, in `arks-make` I did not remove `|&` section. I only replaced /usr/bin/time to time. Please note that, this success was from using `bash 4.2.46 `(as you mentioned). If you were successful with higher version, it would mean that `|&` passed and you would only need to tweak the `time` ! Else, may be something to do with compatability of both bash + gcc version

**Comment by lcoombe** [comment]
Sounds good -- Thanks for the report @arunprasanna83!

**Comment by arunprasanna83** [comment]
> Sounds good -- Thanks for the report @arunprasanna83!

You are welcome @lcoombe !
