### ISSUE TITLE
Running arks / arcs / tigmint with multiple 10X libraries

### ISSUE THREAD

**Issue by iwohlers** [bcgsc/arks#16]
Hi all,
I would like to run tigmint (and later arks) on a human draft assembly. I have several 10x libraries though and as far as I understand I cannot simply merge the files from different libraries, because the same barcodes re-occur, but refer to different molecules. Does tigmint or arks allow input of multiple 10x libraries? 
If not I was considering renaming the barcode names (now they are all  ending with "-1") with "-2", "-3", ... similar to what longranger does (https://support.10xgenomics.com/genome-exome/software/pipelines/latest/advanced/multi-library-samples). Would this work and be correct? Alternatively I could run tigmint and arks multiple times, every time providing only one 10x library, but as far as I understand this is expected to be less precise than providing all 10x data at once. What do you suggest?
Also, using arks is preferable over using arcs, right?
Thanks for your advice!
Inken

**Comment by lcoombe** [comment]
Hi @iwohlers,

Yes, it would be best to use all the libraries at once, and you can distinguish between the libraries as you suggested, with changing the 2nd library read groups to ```-2```, 3rd to ```-3```, etc. Tigmint and ARKS will consider the barcode as anything after the ```BX:Z:``` tag in the read header to the next whitespace.
Either ARCS or ARKS would likely work well for your purpose -- ARKS is faster and easier to use because it doesn't require read alignments, but it doesn't scale as well to large genome assemblies and fragmented assemblies. 

As a side note -- You may have already seen this, but our arks-make Makefile (Examples/arks-make) is very handy for running ARKS or Tigmint+ARKS.

Hope that helps!
Lauren

**Comment by iwohlers** [comment]
Hi Lauren, Thanks for the quick answer, I will do it as you suggested! Inken
